NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"

ACCOUNTS=[
    "GAB4YW6ZBV73IFQDSVYGKOXTLWX67LUDXRAXHUW2U5EXIFCMAWYHEHL7",
    "GCOPQBSS2MZWLB5VSKFVIZQYK76S22OWB75IOJWILRGAW4PUR652G7CI",
]

[DOCUMENTATION]
ORG_URL="https://ananos.tk"
ORG_LOGO="http://ananos.tk/images/logo.jpg"
ORG_DESCRIPTION="The fork of the fork and the people who don't try"
ORG_TWITTER="@AnanosCoin"
ORG_OFFICIAL_EMAIL="ananoscoin@gmail.com"

[[CURRENCIES]]
code="Ananos"
issuer="GAB4YW6ZBV73IFQDSVYGKOXTLWX67LUDXRAXHUW2U5EXIFCMAWYHEHL7"
display_decimals=6
name="Ananos"
desc="The fork of the fork"
conditions="There will be only 28200000000 Ananos tokens in existence."
image="http://ananos.tk/images/logo.jpg"
fixed_number=28200000000

